site_name: СевГУ - П:БПОИ / П:ЯВУ
theme:
  name: material
  palette:
    primary: white
  logo: assets/logo.png
  language: ru

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg