site_name: СевГУ - П:БПОИ / П:ЯВУ
theme:
  name: material
  palette:
    primary: white
  logo: assets/logo.png
  language: ru

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top