site_name: СевГУ - П:БПОИ / П:ЯВУ
site_url: https://readonlyden.github.io/Programming-101
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Включить темную тему
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Включить светлую тему
  logo: assets/logo.png
  language: ru

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true



copyright: "Сделано с &#10084; на кафедре ИТиКС"

extra:
  analytics:
    provider: google
    property: G-44C4RXEXJJ

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/readonlyden/Programming-101
    - icon: fontawesome/brands/vk
      link: https://vk.com/sevsu_itiks
    - icon: fontawesome/solid/link
      link: https://www.sevsu.ru/

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js